accounts/urls.py
from django.urls import path

from accounts.views import logout_view, RegistrationView, LoginView, ProfileView, CretePost, UserChangeView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('post/', CretePost.as_view(), name='post'),
    path('profile/<int:pk>/change', UserChangeView.as_view(), name='change'),
]

api/urls.py
from django.urls import path

from api.views import AccountSimpleView, CommentSimpleView, LikeSimpleView, SubscribeSimpleView, PostSimpleView

urlpatterns = [
    path('account/', AccountSimpleView.as_view(), name='account_view'),
    path('comment/', CommentSimpleView.as_view(), name='comment_view'),
    path('like/', LikeSimpleView.as_view(), name='like_view'),
    path('posts/', PostSimpleView.as_view(), name='post_view'),
    path('subcribe/', SubscribeSimpleView.as_view(), name='subscribe_view')
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('', include('webapp.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                             document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from accounts.managers import UserManager


class Account(AbstractUser):
    GENDER_CHOICES = [
        ('Man', 'Man'),
        ('Women', 'Women'),
        ('Other', 'Other'),
    ]
    gender = models.CharField(max_length=30, choices=GENDER_CHOICES, null=True, blank=True)
    inform = models.CharField(max_length=255, null=True, blank=True)
    phone = models.CharField(null=True, blank=True, verbose_name='Phone')
    language = models.CharField(max_length=100, null=True, blank=True, verbose_name='language')
    email = models.EmailField(verbose_name='Email', unique=True, blank=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pic', verbose_name='Avatar')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Bithday')
    subscribers_count = models.PositiveIntegerField(
        default=0,
        verbose_name='Счетчик подписчиков'
    )
    subscriptions_count = models.PositiveIntegerField(
        default=0,
        verbose_name='Счетчик подписок'
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    object = UserManager()

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from posts.models import Post


class LoginForm(forms.Form):
    email = forms.CharField(required=True, label='Email')
    password = forms.CharField(required=True, label='Password', widget=forms.PasswordInput)


class CustomUserCreateForm(forms.ModelForm):
    GENDER_CHOICE = [
        ('Man', 'Man'),
        ('Women', 'Women'),
        ('Other', 'Other')
    ]
    gender = forms.ChoiceField(label='Gender', choices=GENDER_CHOICE)
    password = forms.CharField(required=True, label='Password', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(required=True, label='Confirm password', strip=False, widget=forms.PasswordInput)
    inform = forms.CharField(required=False, label='Information')
    phone = forms.CharField(label='Phone')
    username = forms.CharField(label='Login')
    first_name = forms.CharField(label='First name')
    last_name = forms.CharField(label='Last name')
    language = forms.CharField(label='Language', required=False)

    class Meta:
        model = get_user_model()
        fields = ('username', 'last_name', 'email', 'password', 'password_confirm', 'first_name', 'birth_date', 'phone',
                  'inform', 'gender', 'avatar', 'language')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Password mismatch!')

    def save(self, commit=True):
        user = super().save(commit=False)
        print(user)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'email', 'avatar', 'birth_date', 'username')
        labels = {'first_name': 'name', 'last_name': 'last_name', 'email': 'Email'}


class PostForm(forms.ModelForm):
    descriptions = forms.CharField(required=False, label='Описание')

    class Meta:
        model = Post
        fields = ('descriptions', 'image',)
        labels = {
            'image': 'Фото',
            'descriptions': 'Описание'
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login, get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView

from accounts.forms import LoginForm, PostForm, UserChangeForm

from accounts.forms import CustomUserCreateForm
from posts.models import Post
from webapp.models import Subscription


class LoginView(TemplateView):
    template_name = 'login.html'
    form = LoginForm

    def get(self, request, *args, **kwargs):
        form = self.form
        context = {'form': form}
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if not form.is_valid():
            return redirect('login')
        username = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if not user:
            messages.error(request, 'Пользователь не найден')
            return redirect('login')
        messages.success(request, 'Добро пожаловать!')
        login(request, user)
        return redirect('index')


def logout_view(request):
    logout(request)
    return redirect('index')


class RegistrationView(CreateView):
    template_name = 'register.html'
    form_class = CustomUserCreateForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(self.success_url)
        else:
            print(form.errors)
        context = {'form': form}
        return self.render_to_response(context)


class CretePost(CreateView):
    model = Post
    template_name = 'crete_post.html'
    form_class = PostForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = self.request.user
            form.save()
            return redirect('/')
        context = {'form': form}
        return self.render_to_response(context)


class ProfileView(DetailView, PermissionRequiredMixin):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    permission_required = 'accounts.user_change'
    permission_denied_message = 'У вас не хватает прав доступа'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['posts'] = self.object.posts.all()
        subscription = Subscription.objects.filter(subscriber=self.request.user, subscribed_to=user).first()
        context['subscription'] = subscription
        return context


class UserChangeView(UpdateView, PermissionRequiredMixin):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    # def get_queryset(self):
    #     return Post.objects.prefetch_related('comments')

    def get_success_url(self):
        return reverse('profile', kwargs={'pk': self.object.pk})

accounts/templates/crete_post.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="text-center mt-3">
                        <button type="submit" class="btn btn-primary">Опубликовать</button>
                        <a href="{% url 'profile' user.id %}" class="btn btn-secondary">Назад</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block menu %}
{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title">Authenticate</h2>
                    <form method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        <div class="form-group mt-3">
                            {% bootstrap_button button_type='submit' content='Sign In' style='width: 200px; background-color: #4cb6f9'%}
                            <a href="{% url 'register' %}" class="btn btn-light ml-2" >Sign Up</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/register.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="registration-container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    {% for field in form.visible_fields|slice:":6" %}
                        <div class="form-group">
                            {% bootstrap_field field layout='horizontal' %}
                        </div>
                    {% endfor %}
                </div>
               <div class="col-md-6">
    {% for field in form.visible_fields|slice:"6:" %}
        <div class="form-group">
            {% if field.name == 'phone' %}
                <label for="{{ field.id_for_label }}">Phone</label>
                <input type="number" class="form-control" id="{{ field.id_for_label }}" name="{{ field.html_name }}" required>
            {% elif field.name == 'language' %}
                <label for="{{ field.id_for_label }}">Language</label>
                <input type="text" class="form-control typeahead" id="{{ field.id_for_label }}" name="{{ field.html_name }}" required>
            {% else %}
                {% bootstrap_field field layout='horizontal' %}
            {% endif %}
        </div>
    {% endfor %}
</div>

            </div>
            <div class="d-grid gap-2">
                {% bootstrap_button button_type='submit' style="background-color: #4cb6f9; width: 380px" content='Sign Up' %}
            </div>
        </form>
    </div>
    <script>
        // Инициализация intl-tel-input
        var input = document.querySelector("#id_phone");
        var iti = window.intlTelInput(input, {
            initialCountry: "auto",
            separateDialCode: true,
            utilsScript: "https://cdnjs.cloudflare.com/ajax/libs/intl-tel-input/17.0.3/js/utils.js"
        });
    </script>
    <script>
        // Инициализация Typeahead.js на поле языка
        var languages = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.whitespace,
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            local: [
                "English", "Spanish", "French", "German", "Russian", "Казахстан", "Kazakhstan"
            ]
        });

        $('#id_language').typeahead({
            hint: true,
            highlight: true,
            minLength: 1
        }, {
            name: 'languages',
            source: languages
        });
    </script>
{% endblock %}

accounts/templates/search_results.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <h1>Search Results</h1>
    <ul>
      {% for user in users %}
        <li>
          <a href="{% url 'profile' user.pk %}">{{ user.username }}</a>
        </li>
      {% empty %}
        <li>No users found.</li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

accounts/templates/user_change.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block menu %}{% endblock %}
{% block content %}
    <div class="registration-container">
            <form action="{% url 'change' user_obj.pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-grid gap-2">
                    <input type="submit" value="Редактировать">
                </div>
        </form>
        <a href="{% url 'profile' user_obj.pk %}"><div class="back">
                    <input type="submit" value="Вернуться назад">
    </div></a>
    </div>
{% endblock %}

accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block menu %}
{% endblock %}
{% block content %}
    <style>
        .custom-card {
            height: 400px;
            margin: 10px;
            position: relative;
            overflow: hidden;
        }

        .custom-card .card-image {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-size: cover;
            background-position: center;
        }

        .custom-card .card-body {
            padding: 1rem;
        }

        .mfp-img-mobile img {
            max-width: 700px !important;
            max-height: 700px !important;
        }

        .info-box {
            margin-top: 10px;
        }

        .user-avatar {
            margin-bottom: 20px;
        }

        .avatar-image {
            width: 200px;
            height: 200px;
            border-radius: 50%;
        }

        .popup-image {
            max-height: 20vh;
            max-width: 20vw;
        }

        .mfp-resize {
            max-width: 600px; /* Установите желаемую максимальную ширину */
            max-height: 400px; /* Установите желаемую максимальную высоту */
        }
    </style>
    <div class="container" style="width: 1000px">
        <div class="row align-items-start">
            <div class="col-md-2 user-avatar">
                <img src="{{ user_obj.avatar.url }}" alt="Avatar" class="avatar-image">
            </div>
            <div class="col-md-6 user-details" style="margin-left: 130px">
                <div class="row profile-header">
                    <div class="col-md-6">
                        <h2>{{ user_obj.username }}</h2>
                    </div>
                    {% if user.is_authenticated and user == user_obj %}
    <div class="col-md-6">
        <a href="{% url 'change' user_obj.pk %}" class="btn btn-light">Редактировать</a>
    </div>
{% endif %}
                    <div class="col-md-6">
                        {% if user.is_authenticated and user != user_obj %}
                            {% if subscription %}
                                <form method="post" action="{% url 'unsubscribe' subscription.pk %}"
                                      class="subscription_button">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-light border border-dark ms-3 mb-3">
                                        Отписаться
                                    </button>
                                </form>
                            {% else %}
                                <form method="post" action="{% url 'subscribe' user_obj.pk %}"
                                      class="subscription_button">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-light border border-dark ms-3 mb-3">
                                        Подписаться
                                    </button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </div>

                    <div class="row info-box">
                        <div class="col-md-4">
                            <p><strong>{{ posts.count }} публикаций</strong></p>
                        </div>
                        <div class="col-md-4">
                            <p><strong>{{ user_obj.subscribers_count }} подписчиков</strong></p></div>
                        <div class="col-md-4">
                            <p><strong>{{ user_obj.subscriptions_count }} подписок</strong></p>
                        </div>
                    </div>
                    <p><strong>Name:</strong> {{ user_obj.first_name }}</p>
                    <p><strong>Email:</strong> {{ user_obj.email }}</p>
                </div>
            </div>
            <hr>
            <a href="{% url 'post' %}" class="nav-link">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                     class="bi bi-plus-lg" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
                </svg>
                Create post
            </a>

            <div class="row row-cols-1 row-cols-md-3 g-1">
                {% for post in posts %}
                    <div class="col mb-0">
                        <div class="card custom-card">
                            <a href="{{ post.image.url }}" class="popup-image">
                                <div class="card-image" style="background-image: url('{{ post.image.url }}'); "></div>
                            </a>
                            <div class="card-body">
                                <p class="card-text">{{ post.user_obj.descriptions }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/image.js' %}">

    </script>

{% endblock %}